name: build
on:
  - push
jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check-out code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec rspec --format documentation

      - name: Test packaging
        run: bundle exec gem build secret_string.gemspec

  semantic_release:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Check-out code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install semantic-release
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/exec semantic-release-rubygem -D

      - name: Semantic releasing
        run: npx semantic-release
        env:
          GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
